### ISSUE TITLE
Errory podla design manualu

### ISSUE THREAD

**Issue by wormyy** [wormyy/priznanie-digital#56]
https://design-system.service.gov.uk/components/error-summary/

**Comment by wormyy** [comment]
![Screenshot 2020-03-08 at 21 32 31](https://user-images.githubusercontent.com/8556724/76170673-73869a80-6184-11ea-9fdc-cbeb93ca3472.png)

Spravil som prvy screen, takto treba upravti vsetky dalsie.

**Comment by wormyy** [comment]
Rozhodol som sa, ze namiesto Yup budeme pouzivat manualnu validaciu, kedze Yup bol zmateny z toho ze pouzivame text inputy aj na numeric fieldy.

**Comment by martin-starosta** [comment]
Chybove hlasky pridane na ostatne obrazovky. Error summary som dal na osobne udaje a partner. Neviem, ci to ma byt na vsetkych obrazovkach?

Ostava este pridat Errors na stranku Deti a urobit validatory poli podla vstupnych dat. Zatial som spravil len DIC (cislo s dlzkou 9 - 10 cislic)

**Comment by wormyy** [comment]
@martin-starosta spravil si k tomu nejaky PR?
